### PR TITLE
HSA-135293239 Add the Drupal 8 Filters

### PR DESCRIPTION
**Pull request by RobLoach**
We need some filters via #4 .

## Tasks

- [x] t
- [x] clean_class
- [x] clean_id
- [x] format_date
- [x] safe_join

### CODE REVIEW

**Comment by RobLoach** [comment]
Tests passing.

twigshimtests

**Comment by hawkeyetwolf** [comment]
Gorgeous work @RobLoach !

**Comment by hawkeyetwolf** [comment]
@RobLoach, BTW, what is that screenshot from... SimpleTest?

**Comment by RobLoach** [comment]
SimpleTest, yeah.

**Pull request merged**
